### ISSUE TITLE
Allow installing Docker from OS or Docker CE repo

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/ansible-role-install-docker#9]
In some cases you may need to run a newer version of Docker than what is being provided with CentOS. For example, Planter now requires Docker 17.06 (since it uses the `--mount` flag, which was added after 1.12, the version shipped with CentOS 7.x).

Add a new option that allows for picking the docker release / version you want.

Suggestion:

```
docker_repo_type: os    # allow for 'os' or 'ce' repo types
```

**Comment by dougbtv** [comment]
Cool, I'll default it to `os`
